# 主页副标题
subtitle:
  enable: true        # 必须开
  effect: true        # 打字机效果
  sub:                # 副标题内容，可写多行轮播
    - 记录成长，分享技术
    - 持续学习，持续输出


# 头像（把头像图放进 source/images/，如 avatar.png）
avatar:
  img: /images/avatar.png
  effect: true            # 鼠标悬停旋转

# 菜单（格式：菜单名: 路径 || 图标，必须是这种字符串格式）
menu:
  首页: / || fas fa-home
  分类: /categories/ || fas fa-folder-open
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags

# 文章页/首页显示分类
post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: false

post_copyright:
  enable: true
  decode: true   # 改为 true：链接的中文解码显示    

# 顶部导航栏展示搜索框
search:
  use: local_search        # 总开关：选用本地搜索（不填则不显示搜索按钮）
  placeholder: 搜索文章...  # 搜索框提示文字，可选  
local_search:
  preload: true                # 页面打开时预加载索引，体积效率，不设默认 false  

  